//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int employeeNum { get; set; }
        public string employeeNameSurname { get; set; }
        public string employeePhone { get; set; }
        public string title { get; set; }
        public string mail { get; set; }
        public int salary { get; set; }
        public int brancNum { get; set; }
    
        public virtual Branch Branch { get; set; }
    }
}
